/*
 TABLE DROPS
 Budget Manager SYSTEM
 Author: Luis E. Serrano
 Date: December 2022
 Version: 1.0.0
*/

/* Table drops scripts */

DROP TABLE BUDGETMAN."TRANSACTION";
DROP TABLE BUDGETMAN.ACCOUNT;
DROP TABLE BUDGETMAN.USERDATA;
DROP TABLE BUDGETMAN.BANK;
DROP TABLE BUDGETMAN.EXCHGRATE;
DROP TABLE BUDGETMAN.CURRENCY;
DROP TABLE BUDGETMAN.CATEGORIES;
DROP TABLE BUDGETMAN.TRANTYPE;
/