apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend 
    spec:
      containers:
      - name: backend
        image: luserrano/budgetman-backend:1.0.0
        env:
          - name: DB_USER
            value: budgetman
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:    
                name: db-secret
                key: app_pass # value: budgetman
          - name: DB_CONNECT_STRING
            value: database-service:1521/xepdb1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 8500
    targetPort: 8500

