apiVersion: v1
kind: Pod
metadata:
  name: test-frontend
  labels:
    name: test-frontend
spec:
  containers:
  - name: test-frontend
    image: luserrano/budgetman-frontend:1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 80
